language: go

go:
  - go1.9

install: true

go_import_path: github.com/evansb/snapper

notifications:
  email: false

before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get github.com/golang/lint/golint

script:
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race ./...
  - go vet ./...
  - golint -set_exit_status $(go list ./...)

